---

# Homebrew
- name: Install dnsmasq (Homebrew)
  homebrew: name=dnsmasq state=present
  become: true
  become_user: "{{ dnsmasq_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'
- name: Create dnsmasq configuration from sample (Homebrew)
  command: cp /usr/local/opt/dnsmasq/dnsmasq.conf.example /usr/local/etc/dnsmasq.conf creates=/usr/local/etc/dnsmasq.conf
  become: true
  become_user: "{{ dnsmasq_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'
- name: Start dnsmasq (Homebrew)
  shell: "{{ dnsmasq_homebrew_bin }} services start dnsmasq"
  become: true
  become_user: root
  register: result
  changed_when: result.rc != 0
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew is supported)"
  when: ansible_pkg_mgr != 'homebrew'
